# Generated by Django 5.1.4 on 2025-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('jan', models.FloatField(default=0)),
                ('feb', models.FloatField(default=0)),
                ('mar', models.FloatField(default=0)),
                ('apr', models.FloatField(default=0)),
                ('may', models.FloatField(default=0)),
                ('june', models.FloatField(default=0)),
                ('july', models.FloatField(default=0)),
                ('aug', models.FloatField(default=0)),
                ('sept', models.FloatField(default=0)),
                ('oct', models.FloatField(default=0)),
                ('nov', models.FloatField(default=0)),
                ('dec', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
    ]
