# Generated by Django 5.1.4 on 2025-10-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.FloatField()),
                ('location', models.CharField(default='Zone A', max_length=100)),
            ],
        ),
    ]
