# Generated by Django 5.1.4 on 2025-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('festival', 'Festival')], default='light', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
