# Generated by Django 5.1.4 on 2025-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptheme',
            name='name',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('festival', 'Festival'), ('diwali', 'Diwali')], default='light', max_length=20),
        ),
    ]
